# Generated by Django 3.1.5 on 2021-01-14 17:10

from django.db import migrations, models
import eshop_products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='نام محصول')),
                ('description', models.TextField(verbose_name='توضیحات محصول')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('discounted_price', models.IntegerField(blank=True, null=True, verbose_name='قیمت محصول بعد از تخفیف')),
                ('count', models.IntegerField(verbose_name='تعداد در انبار')),
                ('active', models.BooleanField(default=False, verbose_name='موجود/ناموجود')),
                ('image', models.ImageField(blank=True, null=True, upload_to=eshop_products.models.upload_image_path, verbose_name='تصویر محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'ماژول محصولات',
            },
        ),
    ]
