# Generated by Django 3.1.5 on 2021-01-15 17:23

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0002_auto_20210114_1716'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='count',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ اضافه شدن محصول'),
        ),
    ]
