# Generated by Django 3.1.5 on 2021-01-17 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eshop_products', '0003_auto_20210115_1723'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sell_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد فروش محصول'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام\u200cخانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('comment', models.TextField(verbose_name='نظر')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ اضافه شدن نظر')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'نظر کاربر',
                'verbose_name_plural': 'نظرات کاربران',
            },
        ),
    ]
