# Generated by Django 3.1.5 on 2021-01-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0006_auto_20210117_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='نظر'),
        ),
    ]
