# Generated by Django 3.1.5 on 2021-01-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_category', '0001_initial'),
        ('eshop_products', '0007_auto_20210118_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='eshop_products_category.ProductCategory', verbose_name='دسته\u200cبندی'),
        ),
    ]
