# Generated by Django 3.1.5 on 2021-01-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_category', '0002_subcategory'),
        ('eshop_products', '0008_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_categories',
            field=models.ManyToManyField(blank=True, null=True, to='eshop_products_category.SubCategory', verbose_name='زیر دسته\u200cبندی'),
        ),
    ]
