# Generated by Django 3.1.5 on 2021-03-02 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0010_product_visit_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visited_Ip_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.TextField(verbose_name='آدرس\u200cها')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop_products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'آدرس ip کاربر',
                'verbose_name_plural': 'آدرس ip کاربر',
            },
        ),
    ]
