# Generated by Django 3.1.5 on 2021-01-19 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'تگ', 'verbose_name_plural': 'تگ\u200cهای محصولات'},
        ),
    ]
