# Generated by Django 3.1.5 on 2021-01-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده/نشده'),
        ),
    ]
