# Generated by Django 3.1.5 on 2021-01-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_contact', '0002_auto_20210121_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='Text',
            new_name='text',
        ),
    ]
