# Generated by Django 3.1.5 on 2021-01-20 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان در url')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='eshop_products_category.productcategory', verbose_name='دسته\u200c اصلی')),
            ],
            options={
                'verbose_name': 'زیردسته\u200cبندی',
                'verbose_name_plural': 'زیردسته\u200cبندی\u200c\u200cها',
            },
        ),
    ]
