# Generated by Django 3.1.5 on 2021-03-13 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eshop_products', '0012_auto_20210302_1647'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30, verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='کد تخفیف')),
                ('amount', models.IntegerField(verbose_name='میزان تخفیف')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کد\u200cهای تخفیف',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده/پرداخت نشده')),
                ('payment_date', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('tracking_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد رهگیری سفارش')),
                ('use_code', models.BooleanField(blank=True, default=False, null=True, verbose_name='استفاده/عدم استفاده از کد تخفیف')),
                ('is_send', models.BooleanField(blank=True, default=False, null=True, verbose_name='ارسال شده/نشده')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='نام')),
                ('family', models.CharField(max_length=50, null=True, verbose_name=' نام\u200cخانوادگی')),
                ('post_code', models.IntegerField(null=True, verbose_name='کد پستی')),
                ('phone_number', models.IntegerField(null=True, verbose_name='شماره همراه')),
                ('address', models.TextField(null=True, verbose_name='آدرستوضیحات')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop_order.city', verbose_name='شهر')),
                ('coupon_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eshop_order.coupon', verbose_name='کد تخفیف')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری خریدار')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبد خرید کاربران',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=30, verbose_name='استان')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان\u200cها',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('count', models.IntegerField(verbose_name='تعداد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_order.order', verbose_name='سبد خرید')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'جزئیات سبد خرید',
                'verbose_name_plural': 'اطلاعات جزئیات سبد خرید',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop_order.province', verbose_name='استان'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_order.province', verbose_name='استان'),
        ),
    ]
