# Generated by Django 3.1.5 on 2021-03-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0002_auto_20210304_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeorderuser',
            name='family',
            field=models.CharField(max_length=50, verbose_name=' نام\u200cخانوادگی'),
        ),
    ]
