# Generated by Django 3.1.5 on 2021-03-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0003_auto_20210304_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeorderuser',
            name='family',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' نام\u200cخانوادگی'),
        ),
        migrations.AlterField(
            model_name='completeorderuser',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام'),
        ),
    ]
