# Generated by Django 3.1.5 on 2021-03-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0005_auto_20210304_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeorderuser',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
    ]
