# Generated by Django 3.1.5 on 2021-03-06 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0006_auto_20210305_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop_order.city', verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='order',
            name='family',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' نام\u200cخانوادگی'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره همراه'),
        ),
        migrations.AddField(
            model_name='order',
            name='post_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='کد پستی'),
        ),
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop_order.province', verbose_name='استان'),
        ),
    ]
